apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
  namespace: infra
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kafka-init
        image: apache/kafka:latest
        command:
          - sh
          - -c
          - |
            /opt/kafka/bin/kafka-topics.sh \
              --bootstrap-server kafka.infra.svc.cluster.local:9092 \
              --create \
              --if-not-exists \
              --topic order-created \
              --replication-factor 1 \
              --partitions 1
