apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: infra
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: plaintext
      port: 9092
    - name: controller
      port: 9093
    - name: external
      port: 9097
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: infra
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:latest
        ports:
          - containerPort: 9092
          - containerPort: 9093
          - containerPort: 9097
        env:
          - name: KAFKA_NODE_ID
            value: "1"
          - name: KAFKA_PROCESS_ROLES
            value: "broker,controller"
          - name: KAFKA_CONTROLLER_QUORUM_VOTERS
            value: "1@kafka-0.kafka.infra.svc.cluster.local:9093"
          - name: KAFKA_CONTROLLER_LISTENER_NAMES
            value: "CONTROLLER"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092,CONTROLLER://:9093"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-0.kafka.infra.svc.cluster.local:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "PLAINTEXT"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
        volumeMounts:
          - name: kafka-data
            mountPath: /var/lib/kafka/data
      volumes:
        - name: kafka-data
          hostPath:
            path: /run/desktop/mnt/host/c/kafka-data
            type: DirectoryOrCreate
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
