apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: mdsajjad217/orderservice:latest
        ports:
          - containerPort: 8081
        env:
          - name: Kafka__BootstrapServers
            value: "kafka.infra.svc.cluster.local:9092"

          - name: Kafka__Acks
            value: "All"

          - name: Kafka__EnableIdempotence
            value: "true"

          - name: Kafka__MessageSendMaxRetries
            value: "3"

          - name: Kafka__RetryBackoffMs
            value: "100"   # MUST be >= 1

          - name: Kafka__LingerMs
            value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: apps
spec:
  selector:
    app: orderservice
  ports:
    - port: 8081
